### ISSUE TITLE
two bugs after recent changes

### ISSUE THREAD

**Issue by loetmeister** [fredlcore/bsb_lan#103]
+ The current version does not compile without LOGGER defined
fix:
https://github.com/loetmeister/bsb_lan/commit/4519582a9e445e45101529e568bc4951176e8f00

+ 24h averages (avg_parameters) are queried constantly, not every minute
fix:
https://github.com/loetmeister/bsb_lan/commit/d081c230f62d9eae6e16aba2d2f02a85e3a7476d

**Comment by fredlcore** [comment]
Thanks, included the second one in latest commit, the first one had to happen a bit earlier, I guess, see also latest commit.
As a general request to whoever adds to the code: Please be very careful with idention (2 spaces for each level). The logger code was wrong by one or more levels and this really makes bugfixing hard. I can live with a lot of "optimized" code that is in my opinion harder to read (like the VAR?A:B shorthand for a good old-fashioned if-then-else block, but proper indention is a must (and the only thing I like about python ;) )...
