### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by matzeeg3** [fredlcore/bsb_lan#166]
Hi if i try to compile i get the following error:
`C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint_farptr_t calc_enum_offset(uint_farptr_t, uint16_t)':

BSB_lan:802:27: error: 'pgm_read_byte_far' was not declared in this scope

     uint8_t second_char = pgm_read_byte_far(enum_addr + page + 1);

                           ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:802:27: note: suggested alternative: 'pgm_read_byte_near'

     uint8_t second_char = pgm_read_byte_far(enum_addr + page + 1);

                           ^~~~~~~~~~~~~~~~~

                           pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint32_t get_cmdtbl_cmd(int)':

BSB_lan:879:9: error: 'pgm_read_dword_far' was not declared in this scope

     c = pgm_read_dword_far(pgm_get_far_address(cmdtbl1[0].cmd) + i * sizeof(cmdtbl1[0]));

         ^~~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:879:9: note: suggested alternative: 'pgm_read_dword_near'

     c = pgm_read_dword_far(pgm_get_far_address(cmdtbl1[0].cmd) + i * sizeof(cmdtbl1[0]));

         ^~~~~~~~~~~~~~~~~~

         pgm_read_dword_near

BSB_lan:885:9: error: 'pgm_read_dword_far' was not declared in this scope

     c = pgm_read_dword_far(pgm_get_far_address(cmdtbl2[0].cmd) + (i - entries1) * sizeof(cmdtbl2[0]));

         ^~~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:885:9: note: suggested alternative: 'pgm_read_dword_near'

     c = pgm_read_dword_far(pgm_get_far_address(cmdtbl2[0].cmd) + (i - entries1) * sizeof(cmdtbl2[0]));

         ^~~~~~~~~~~~~~~~~~

         pgm_read_dword_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint16_t get_cmdtbl_line(int)':

BSB_lan:899:9: error: 'pgm_read_word_far' was not declared in this scope

     l = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].line) + i * sizeof(cmdtbl1[0]));

         ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:899:9: note: suggested alternative: 'pgm_read_word_near'

     l = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].line) + i * sizeof(cmdtbl1[0]));

         ^~~~~~~~~~~~~~~~~

         pgm_read_word_near

BSB_lan:905:9: error: 'pgm_read_word_far' was not declared in this scope

     l = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].line) + (i - entries1) * sizeof(cmdtbl2[0]));

         ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:905:9: note: suggested alternative: 'pgm_read_word_near'

     l = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].line) + (i - entries1) * sizeof(cmdtbl2[0]));

         ^~~~~~~~~~~~~~~~~

         pgm_read_word_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint_farptr_t get_cmdtbl_desc(int)':

BSB_lan:918:12: error: 'pgm_read_word_far' was not declared in this scope

     desc = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].desc) + i * sizeof(cmdtbl1[0]));

            ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:918:12: note: suggested alternative: 'pgm_read_word_near'

     desc = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].desc) + i * sizeof(cmdtbl1[0]));

            ^~~~~~~~~~~~~~~~~

            pgm_read_word_near

BSB_lan:924:12: error: 'pgm_read_word_far' was not declared in this scope

     desc = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].desc) + (i - entries1) * sizeof(cmdtbl2[0]));

            ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:924:12: note: suggested alternative: 'pgm_read_word_near'

     desc = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].desc) + (i - entries1) * sizeof(cmdtbl2[0]));

            ^~~~~~~~~~~~~~~~~

            pgm_read_word_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint_farptr_t get_cmdtbl_enumstr(int)':

BSB_lan:937:15: error: 'pgm_read_word_far' was not declared in this scope

     enumstr = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].enumstr) + i * sizeof(cmdtbl1[0]));

               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:937:15: note: suggested alternative: 'pgm_read_word_near'

     enumstr = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].enumstr) + i * sizeof(cmdtbl1[0]));

               ^~~~~~~~~~~~~~~~~

               pgm_read_word_near

BSB_lan:943:15: error: 'pgm_read_word_far' was not declared in this scope

     enumstr = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].enumstr) + (i - entries1) * sizeof(cmdtbl2[0]));

               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:943:15: note: suggested alternative: 'pgm_read_word_near'

     enumstr = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].enumstr) + (i - entries1) * sizeof(cmdtbl2[0]));

               ^~~~~~~~~~~~~~~~~

               pgm_read_word_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint16_t get_cmdtbl_enumstr_len(int)':

BSB_lan:956:19: error: 'pgm_read_word_far' was not declared in this scope

     enumstr_len = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].enumstr_len) + i * sizeof(cmdtbl1[0]));

                   ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:956:19: note: suggested alternative: 'pgm_read_word_near'

     enumstr_len = pgm_read_word_far(pgm_get_far_address(cmdtbl1[0].enumstr_len) + i * sizeof(cmdtbl1[0]));

                   ^~~~~~~~~~~~~~~~~

                   pgm_read_word_near

BSB_lan:962:19: error: 'pgm_read_word_far' was not declared in this scope

     enumstr_len = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].enumstr_len) + (i - entries1) * sizeof(cmdtbl2[0]));

                   ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:962:19: note: suggested alternative: 'pgm_read_word_near'

     enumstr_len = pgm_read_word_far(pgm_get_far_address(cmdtbl2[0].enumstr_len) + (i - entries1) * sizeof(cmdtbl2[0]));

                   ^~~~~~~~~~~~~~~~~

                   pgm_read_word_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint8_t get_cmdtbl_category(int)':

BSB_lan:977:11: error: 'pgm_read_byte_far' was not declared in this scope

     cat = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].category) + i * sizeof(cmdtbl1[0]));

           ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:977:11: note: suggested alternative: 'pgm_read_byte_near'

     cat = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].category) + i * sizeof(cmdtbl1[0]));

           ^~~~~~~~~~~~~~~~~

           pgm_read_byte_near

BSB_lan:983:11: error: 'pgm_read_byte_far' was not declared in this scope

     cat = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].category) + (i - entries1) * sizeof(cmdtbl2[0]));

           ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:983:11: note: suggested alternative: 'pgm_read_byte_near'

     cat = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].category) + (i - entries1) * sizeof(cmdtbl2[0]));

           ^~~~~~~~~~~~~~~~~

           pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint8_t get_cmdtbl_type(int)':

BSB_lan:996:12: error: 'pgm_read_byte_far' was not declared in this scope

     type = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].type) + i * sizeof(cmdtbl1[0]));

            ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:996:12: note: suggested alternative: 'pgm_read_byte_near'

     type = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].type) + i * sizeof(cmdtbl1[0]));

            ^~~~~~~~~~~~~~~~~

            pgm_read_byte_near

BSB_lan:1002:12: error: 'pgm_read_byte_far' was not declared in this scope

     type = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].type) + (i - entries1) * sizeof(cmdtbl2[0]));

            ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1002:12: note: suggested alternative: 'pgm_read_byte_near'

     type = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].type) + (i - entries1) * sizeof(cmdtbl2[0]));

            ^~~~~~~~~~~~~~~~~

            pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint8_t get_cmdtbl_dev_fam(int)':

BSB_lan:1015:15: error: 'pgm_read_byte_far' was not declared in this scope

     dev_fam = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].dev_fam) + i * sizeof(cmdtbl1[0]));

               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1015:15: note: suggested alternative: 'pgm_read_byte_near'

     dev_fam = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].dev_fam) + i * sizeof(cmdtbl1[0]));

               ^~~~~~~~~~~~~~~~~

               pgm_read_byte_near

BSB_lan:1021:15: error: 'pgm_read_byte_far' was not declared in this scope

     dev_fam = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].dev_fam) + (i - entries1) * sizeof(cmdtbl2[0]));

               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1021:15: note: suggested alternative: 'pgm_read_byte_near'

     dev_fam = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].dev_fam) + (i - entries1) * sizeof(cmdtbl2[0]));

               ^~~~~~~~~~~~~~~~~

               pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint8_t get_cmdtbl_dev_var(int)':

BSB_lan:1034:15: error: 'pgm_read_byte_far' was not declared in this scope

     dev_var = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].dev_var) + i * sizeof(cmdtbl1[0]));

               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1034:15: note: suggested alternative: 'pgm_read_byte_near'

     dev_var = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].dev_var) + i * sizeof(cmdtbl1[0]));

               ^~~~~~~~~~~~~~~~~

               pgm_read_byte_near

BSB_lan:1040:15: error: 'pgm_read_byte_far' was not declared in this scope

     dev_var = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].dev_var) + (i - entries1) * sizeof(cmdtbl2[0]));

               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1040:15: note: suggested alternative: 'pgm_read_byte_near'

     dev_var = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].dev_var) + (i - entries1) * sizeof(cmdtbl2[0]));

               ^~~~~~~~~~~~~~~~~

               pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'uint8_t get_cmdtbl_flags(int)':

BSB_lan:1053:13: error: 'pgm_read_byte_far' was not declared in this scope

     flags = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].flags) + i * sizeof(cmdtbl1[0]));

             ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1053:13: note: suggested alternative: 'pgm_read_byte_near'

     flags = pgm_read_byte_far(pgm_get_far_address(cmdtbl1[0].flags) + i * sizeof(cmdtbl1[0]));

             ^~~~~~~~~~~~~~~~~

             pgm_read_byte_near

BSB_lan:1059:13: error: 'pgm_read_byte_far' was not declared in this scope

     flags = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].flags) + (i - entries1) * sizeof(cmdtbl2[0]));

             ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1059:13: note: suggested alternative: 'pgm_read_byte_near'

     flags = pgm_read_byte_far(pgm_get_far_address(cmdtbl2[0].flags) + (i - entries1) * sizeof(cmdtbl2[0]));

             ^~~~~~~~~~~~~~~~~

             pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void loadPrognrElementsFromTable(int)':

BSB_lan:1324:29: error: 'pgm_read_byte_far' was not declared in this scope

   decodedTelegram.data_type=pgm_read_byte_far(pgm_get_far_address(optbl[0].data_type) + decodedTelegram.type * sizeof(optbl[0]));

                             ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1324:29: note: suggested alternative: 'pgm_read_byte_near'

   decodedTelegram.data_type=pgm_read_byte_far(pgm_get_far_address(optbl[0].data_type) + decodedTelegram.type * sizeof(optbl[0]));

                             ^~~~~~~~~~~~~~~~~

                             pgm_read_byte_near

BSB_lan:1326:27: error: 'pgm_read_float_far' was not declared in this scope

   decodedTelegram.operand=pgm_read_float_far(pgm_get_far_address(optbl[0].operand) + decodedTelegram.type * sizeof(optbl[0]));

                           ^~~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1326:27: note: suggested alternative: 'pgm_read_float_near'

   decodedTelegram.operand=pgm_read_float_far(pgm_get_far_address(optbl[0].operand) + decodedTelegram.type * sizeof(optbl[0]));

                           ^~~~~~~~~~~~~~~~~~

                           pgm_read_float_near

BSB_lan:1333:35: error: 'pgm_read_word_far' was not declared in this scope

   strcpy_PF(decodedTelegram.unit, pgm_read_word_far(pgm_get_far_address(optbl[0].unit) + decodedTelegram.type * sizeof(optbl[0])));

                                   ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1333:35: note: suggested alternative: 'pgm_read_word_near'

   strcpy_PF(decodedTelegram.unit, pgm_read_word_far(pgm_get_far_address(optbl[0].unit) + decodedTelegram.type * sizeof(optbl[0])));

                                   ^~~~~~~~~~~~~~~~~

                                   pgm_read_word_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void printENUM(uint_farptr_t, uint16_t, uint16_t, int)':

BSB_lan:1939:17: error: 'pgm_read_byte_far' was not declared in this scope

       if((byte)(pgm_read_byte_far(enumstr+c+1))!=' '){

                 ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1939:17: note: suggested alternative: 'pgm_read_byte_near'

       if((byte)(pgm_read_byte_far(enumstr+c+1))!=' '){

                 ^~~~~~~~~~~~~~~~~

                 pgm_read_byte_near

BSB_lan:1951:13: error: 'pgm_read_byte_far' was not declared in this scope

       while(pgm_read_byte_far(enumstr+c)!=0) c++;

             ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:1951:13: note: suggested alternative: 'pgm_read_byte_near'

       while(pgm_read_byte_far(enumstr+c)!=0) c++;

             ^~~~~~~~~~~~~~~~~

             pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void printCustomENUM(uint_farptr_t, uint16_t, uint16_t, int)':

BSB_lan:2044:11: error: 'pgm_read_byte_far' was not declared in this scope

       val=pgm_read_byte_far(enumstr+c+1);

           ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:2044:11: note: suggested alternative: 'pgm_read_byte_near'

       val=pgm_read_byte_far(enumstr+c+1);

           ^~~~~~~~~~~~~~~~~

           pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void printTelegram(byte*, int)':

BSB_lan:2645:31: error: 'pgm_read_byte_far' was not declared in this scope

                 uint8_t idx = pgm_read_byte_far(enumstr_ptr+0);

                               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:2645:31: note: suggested alternative: 'pgm_read_byte_near'

                 uint8_t idx = pgm_read_byte_far(enumstr_ptr+0);

                               ^~~~~~~~~~~~~~~~~

                               pgm_read_byte_near

BSB_lan:2659:31: error: 'pgm_read_byte_far' was not declared in this scope

                 uint8_t idx = pgm_read_byte_far(enumstr_ptr+0);

                               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:2659:31: note: suggested alternative: 'pgm_read_byte_near'

                 uint8_t idx = pgm_read_byte_far(enumstr_ptr+0);

                               ^~~~~~~~~~~~~~~~~

                               pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void printPStr(uint_farptr_t, uint16_t)':

BSB_lan:2771:27: error: 'pgm_read_byte_far' was not declared in this scope

     bigBuff[bigBuffPos] = pgm_read_byte_far(outstr+x);

                           ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:2771:27: note: suggested alternative: 'pgm_read_byte_near'

     bigBuff[bigBuffPos] = pgm_read_byte_far(outstr+x);

                           ^~~~~~~~~~~~~~~~~

                           pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void LogTelegram(byte*)':

BSB_lan:3114:21: error: 'pgm_read_float_far' was not declared in this scope

             operand=pgm_read_float_far(pgm_get_far_address(optbl[0].operand) + cmd_type * sizeof(optbl[0]));

                     ^~~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:3114:21: note: suggested alternative: 'pgm_read_float_near'

             operand=pgm_read_float_far(pgm_get_far_address(optbl[0].operand) + cmd_type * sizeof(optbl[0]));

                     ^~~~~~~~~~~~~~~~~~

                     pgm_read_float_near

BSB_lan:3115:23: error: 'pgm_read_byte_far' was not declared in this scope

             precision=pgm_read_byte_far(pgm_get_far_address(optbl[0].precision) + cmd_type * sizeof(optbl[0]));

                       ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:3115:23: note: suggested alternative: 'pgm_read_byte_near'

             precision=pgm_read_byte_far(pgm_get_far_address(optbl[0].precision) + cmd_type * sizeof(optbl[0]));

                       ^~~~~~~~~~~~~~~~~

                       pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'int set(int, const char*, bool)':

BSB_lan:3734:21: error: 'pgm_read_byte_far' was not declared in this scope

       uint8_t idx = pgm_read_byte_far(enumstr_ptr+0);

                     ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:3734:21: note: suggested alternative: 'pgm_read_byte_near'

       uint8_t idx = pgm_read_byte_far(enumstr_ptr+0);

                     ^~~~~~~~~~~~~~~~~

                     pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void query_printHTML()':

BSB_lan:3941:25: error: 'pgm_read_byte_far' was not declared in this scope

               if((byte)(pgm_read_byte_far(decodedTelegram.enumstr+c+1))!=' ' || decodedTelegram.type == VT_BIT){         // ENUMs must not contain two consecutive spaces! Necessary because VT_BIT bitmask may be 0x20 which equals space

                         ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:3941:25: note: suggested alternative: 'pgm_read_byte_near'

               if((byte)(pgm_read_byte_far(decodedTelegram.enumstr+c+1))!=' ' || decodedTelegram.type == VT_BIT){         // ENUMs must not contain two consecutive spaces! Necessary because VT_BIT bitmask may be 0x20 which equals space

                         ^~~~~~~~~~~~~~~~~

                         pgm_read_byte_near

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino: In function 'void loop()':

BSB_lan:5708:25: error: 'pgm_read_word_far' was not declared in this scope

               cat_min = pgm_read_word_far(pgm_get_far_address(ENUM_CAT_NR) + (cat*2) * sizeof(ENUM_CAT_NR[0]));

                         ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:5708:25: note: suggested alternative: 'pgm_read_word_near'

               cat_min = pgm_read_word_far(pgm_get_far_address(ENUM_CAT_NR) + (cat*2) * sizeof(ENUM_CAT_NR[0]));

                         ^~~~~~~~~~~~~~~~~

                         pgm_read_word_near

BSB_lan:5739:27: error: 'pgm_read_byte_far' was not declared in this scope

                 if((byte)(pgm_read_byte_far(enumstr+c+1))!=' '){

                           ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:5739:27: note: suggested alternative: 'pgm_read_byte_near'

                 if((byte)(pgm_read_byte_far(enumstr+c+1))!=' '){

                           ^~~~~~~~~~~~~~~~~

                           pgm_read_byte_near

BSB_lan:5740:23: error: 'pgm_read_word_far' was not declared in this scope

                   val=pgm_read_word_far(enumstr+c);

                       ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:5740:23: note: suggested alternative: 'pgm_read_word_near'

                   val=pgm_read_word_far(enumstr+c);

                       ^~~~~~~~~~~~~~~~~

                       pgm_read_word_near

BSB_lan:6194:31: error: 'pgm_read_word_far' was not declared in this scope

                     cat_min = pgm_read_word_far(pgm_get_far_address(ENUM_CAT_NR) + (cat*2) * sizeof(ENUM_CAT_NR[0]));

                               ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:6194:31: note: suggested alternative: 'pgm_read_word_near'

                     cat_min = pgm_read_word_far(pgm_get_far_address(ENUM_CAT_NR) + (cat*2) * sizeof(ENUM_CAT_NR[0]));

                               ^~~~~~~~~~~~~~~~~

                               pgm_read_word_near

BSB_lan:6213:29: error: 'pgm_read_word_far' was not declared in this scope

                   cat_min = pgm_read_word_far(pgm_get_far_address(ENUM_CAT_NR) + (search_cat*2) * sizeof(ENUM_CAT_NR[0]));

                             ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:6213:29: note: suggested alternative: 'pgm_read_word_near'

                   cat_min = pgm_read_word_far(pgm_get_far_address(ENUM_CAT_NR) + (search_cat*2) * sizeof(ENUM_CAT_NR[0]));

                             ^~~~~~~~~~~~~~~~~

                             pgm_read_word_near

BSB_lan:6262:35: error: 'pgm_read_byte_far' was not declared in this scope

                         if((byte)(pgm_read_byte_far(enumstr+x+1))!=' ' || decodedTelegram.type == VT_BIT) {         // ENUMs must not contain two consecutive spaces! Necessary because VT_BIT bitmask may be 0x20 which equals space

                                   ^~~~~~~~~~~~~~~~~

C:\Users\matthias\Downloads\BSB_lan\BSB_lan.ino:6262:35: note: suggested alternative: 'pgm_read_byte_near'

                         if((byte)(pgm_read_byte_far(enumstr+x+1))!=' ' || decodedTelegram.type == VT_BIT) {         // ENUMs must not contain two consecutive spaces! Necessary because VT_BIT bitmask may be 0x20 which equals space

                                   ^~~~~~~~~~~~~~~~~

                                   pgm_read_byte_near

exit status 1

'pgm_read_byte_far' was not declared in this scope

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`
any idears?

**Comment by fredlcore** [comment]
Wrong board type selected in the Arduino IDE.
@1coderookie : should we add this error message (just the first one) to the manual / FAQ? I get these "bug reports" once in a while because people press compile before setting all the necessary options?
