### ISSUE TITLE
Please remove leading spaces via MQTT

### ISSUE THREAD

**Issue by FunkOdyssey2001** [fredlcore/bsb_lan#170]
I have several problems,  because there seems to be leading spaces in the MQTT output. 
For example all error strings (e.g. 6800). 
Please see my forum topic here, too: https://forum.fhem.de/index.php/topic,115705.msg1100143.html#msg1100143

**Comment by fredlcore** [comment]
Since the other contributors here don't speak German, it's not helpful to link to a German forum thread. Please describe the errors here in detail as well as observations you may have made. Thanks.

**Comment by FunkOdyssey2001** [comment]
Sorry, but this is really simple. There are always leading spaces before string MQTT output. 

The link should just show the way how I was pointed to this behavior.

**Comment by FunkOdyssey2001** [comment]
Perhaps references with #116

**Comment by dukess** [comment]
In new version i will propose to change DHT22 requests: accessing to sensors will do through programs, i.e. even programs will returns temperature, odd - humidity

**Comment by FunkOdyssey2001** [comment]
> In new version i will propose to change DHT22 requests: accessing to sensors will do through programs, i.e. even programs will returns temperature, odd - humidity

I don't understand this in detail.  Does this have anything to do with the leading spaces?

**Comment by fredlcore** [comment]
Maybe. The whole way of accessing sensors is now through parameter numbers, so these are no longer handled differently. Therefore, the leading space should hopefully disappear. Please check.

**Comment by FunkOdyssey2001** [comment]
I will try the new v2.0 branch soon.

**Comment by FunkOdyssey2001** [comment]
In Version 2.0.14-20201117142051 no differences. There are still leading spaces.

`byte mqtt_mode = 1;` 



```
2020-11-18_16:12:10 bsb History01_FAPhase:  16 - not found
2020-11-18_16:12:07 bsb Betriebsart:  1 - Automatik
```

There are no leading spaces for numeric parameters:

```
2020-11-18_16:02:22 bsb Raumtemperatur1: 21.0
2020-11-18_16:02:22 bsb Vorlaufsollwert1: 19.0
```

**Comment by fredlcore** [comment]
Latest update should fix this.

**Comment by FunkOdyssey2001** [comment]
Thank you very much.
