### ISSUE TITLE
new Value for 8005

### ISSUE THREAD

**Issue by Luposoft63** [fredlcore/bsb_lan#202]
I found out a new value for parameter 8005 (Status Kessel)

220 = "Reglerstopp aktiv"

**Comment by 1coderookie** [comment]
Nice!
But I guess @fredlcore needs the whole commandID/telegram for that value to implement it.. ;)

**Comment by fredlcore** [comment]
@1coderookie: No, in that case it's sufficient because parameter 8005 already exists and we just need to add the ENUM option 220 (0xDC) and the text for it. So thanks, @Luposoft63!
