### ISSUE TITLE
lookup_descr() must be outside of #ifdef IPWE

### ISSUE THREAD

**Issue by stan23** [fredlcore/bsb_lan#21]
The function `lookup_descr()` is used in function `loop()` for the average handling:
https://github.com/fredlcore/bsb_lan/blob/master/BSB_lan/BSB_lan/BSB_lan.ino#L2412

But the function itself is declared/defined guarded by `#ifdef IPWE`, which obviously breaks compilation if `IPWE` is not defined.

**Comment by fredlcore** [comment]
Thanks, I still have to get used to several features of GitHub, and unfortunately, I wasn't notfied of this issue by mail. The problem is solved now in versions 0.23 and above. Thanks for your patience!
