### ISSUE TITLE
allow flexible subnet mask as 255.255.0.0

### ISSUE THREAD

**Issue by riker65** [fredlcore/bsb_lan#25]
Hi
as an enhancement

please allow custom subnet masks to be configured

does this make sense?

Thanks T

**Comment by fredlcore** [comment]
Probably not necessary in most use cases, but no big deal to implement. Most recent master branch has the configuration option in BSB_lan_config.h.default. Please test and let me know if it works so I can close the request.

**Comment by fredlcore** [comment]
Can I close this issue?
