### ISSUE TITLE
/Y command

### ISSUE THREAD

**Issue by dukess** [fredlcore/bsb_lan#289]
Somebody known about it?
I found not nothing in manual

**Comment by 1coderookie** [comment]
Nope, don't remember anything about it right now and didn't find anything within the changelog within the .ino as well :(

**Comment by fredlcore** [comment]
/Y is an internal command to send a command id directly to the bus and display the result.
The syntax is /Yaa,bbbbbbbb where aa is the telegram type (e.g. 06 for TYPE_QUR) and bbbbbbbb is the command ID to be sent.

**Comment by 1coderookie** [comment]
Ha, right - I knew I read and used it somewhere somehow: that were the 'cryptic' commands you sent me sometimes to check something! :)
