### ISSUE TITLE
Broken texts

### ISSUE THREAD

**Issue by fredlcore** [fredlcore/bsb_lan#292]
In some entries of the configuration menu, the first character of the first dropdown entry is cut off. At the same time, the option value of that entry is "0" which is tricky because it still works with "Off" entries (which are zero anyways), but if you look at the QAA model dropdown, the QAA 50 entry does not have the entry 82, but 0 as well.
@dukess: Do you have an idea why this could be the case? The entries in BSB_lan_defs.h and LANG_DE.h look allright to me.

**Comment by 1coderookie** [comment]
Do you mean the entry by the pulldown itself (like Ein/Aus) or the transmitted value/code?
Just tried with v2.0.76-20210114232524 - here everything looks ok within the pulldown entries (checked every pulldown):
![Bildschirmfoto von 2021-01-16 17-38-38](https://user-images.githubusercontent.com/25869362/104817472-c78cf180-5821-11eb-8a45-2d136cff99ac.png)
Tried some switching between on/off (but not with every function though) and also that worked.
Tested with Chrome and FireFox.

**Comment by fredlcore** [comment]
Ok, sorry, I should upload my own devices with the most recent firmware before I make such tests ;), sorry for the confusion, and thanks @1coderookie for double-checking :)!
