### ISSUE TITLE
Inconsistent layout on Q2 in V4 PCB

### ISSUE THREAD

**Issue by BenDrexx** [fredlcore/bsb_lan#293]
Hi there,

I had a look on the schematic and the layout, but one thing confuses me. In the schematic you can see that the Q2's Collector is connected to R3 and the Emitter to VCC, but when you look at the PCBs layout this is complete different, Q2s Collector is there connected to VCC and the Emitter to R3.

Which one is the right, PCB/Layout or Schematic?

![BSB_LAN_inconsistent_layout](https://user-images.githubusercontent.com/19894616/104827275-4010a400-585c-11eb-96d9-6d4bc17d247d.jpg)

**Comment by fredlcore** [comment]
The schematic is correct, the layout has already been fixed in 4.1, I just haven't updated the image yet, because I didn't assume many people to actually check the traces.

The board would run nevertheless because Q2 is a bipolar transistor.
