### ISSUE TITLE
Add warning for missing (new) definements

### ISSUE THREAD

**Issue by fredlcore** [fredlcore/bsb_lan#297]
Could/should we add a section that puts out a compiler warning if a (newly added) config definement (or even variable, if possible) is not yet added to an existing installation? That would make troubleshooting for users easier if they upgrade and do not immediately know what they should add to their existing configuration.

**Comment by dukess** [comment]
The only thing that comes to mind is to add #define with version number to the configuration file, and compare it with the program version number when compiling. If the versions are different, display a warning.

**Comment by fredlcore** [comment]
I was thinking of adding something like this to _defs.h:
```
#if !defined(BUTTONS) || !defined(RGT_EMULALTOR) ...
error "Mandatory definement missing in BSB_lan_config.h - please compare with BSB_lan_config.h.default
#endif
```

**Comment by dukess** [comment]
In this case warning will appear always when user will disable unused modules.

fredlcore <notifications@github.com> 20 января 2021 г. 13:29:35 написал:

**Comment by fredlcore** [comment]
You're right, then let's drop this.
