### ISSUE TITLE
DHT22 never shows all values at the same time

### ISSUE THREAD

**Issue by 1coderookie** [fredlcore/bsb_lan#318]
Hi guys,
can/did someone of you check if a DHT22 works correct with the current version? 
Mine always shows only one value when I query (which value then seems to be chosen randomly, in most cases it's temperature). It never shows all values at the same time. Tested with two different setups.
The sensor itself is ok though, just tested it with a Mega and v0.44 - three values are reported as expected.

**Comment by dukess** [comment]
It is possible that DHT22 cannot transmit data at short intervals. I see two ways: 1. do buffering of data from the sensor; 2. add a delay after accessing the sensor. The second option is easier.

**Comment by dukess** [comment]
Found info: interval between queries must be at least 2 sec.

**Comment by 1coderookie** [comment]
Thanks for answering. That's not the problem though. When I query at the old Mega setup, all three measured values are displayed. Now with Due & the current version, a query only shows one out of three measured values. Doesn't matter if I retry every minute or once in an hour. 
Here some screenshots:
![Bildschirmfoto von 2021-01-29 07-55-10](https://user-images.githubusercontent.com/25869362/106380571-79e0bf00-63b3-11eb-97df-460533112e44.png)
![Bildschirmfoto von 2021-01-29 07-51-28](https://user-images.githubusercontent.com/25869362/106380574-7a795580-63b3-11eb-8a0c-0df43397e4b9.png)
![Bildschirmfoto von 2021-01-29 07-48-25](https://user-images.githubusercontent.com/25869362/106380575-7b11ec00-63b3-11eb-9eac-47f66f52c8bb.png)
 At the hardware side, everything seems to be ok though: sensor, voltage, wiring etc., and everything works fine at the Mega-setup also.
So I was wondering if maybe something was changed back in time that it doesn't work as expected.

**Comment by dukess** [comment]
This PR may help: https://github.com/fredlcore/bsb_lan/pull/319

> Thanks for answering. That's not the problem though. When I query at the old Mega setup, all three measured values are displayed. Now with Due & the current version, a query only shows one out of three measured values. Doesn't matter if I retry every minute or once in an hour.

On version < 2.0 we read DHT22 once per measure temp and humidity.
On version 2.0 we need query every sensor 3 times: when measuring temperature, humidity and abs. humidity. (And here is raised problem: sensor can't be queried so quick)
I add some variables for save state between queries. If we query same sensor multiple times we get values without repeating sensor reads.

**Comment by 1coderookie** [comment]
Ah ok, got it, thanks! I thought you meant the query from my side.. Just because I'm curious: why the sensor has to be read out 3 times at v2.x?
Flashing your ino for testing right now..

**Comment by 1coderookie** [comment]
Now it works! Thanks! ..now I can disconnect that DHT and put it back in the box.. :)
![Bildschirmfoto von 2021-01-31 11-45-42](https://user-images.githubusercontent.com/25869362/106381582-15752e00-63ba-11eb-9d7e-9d58398973ab.png)

**Comment by dukess** [comment]
>Just because I'm curious: why the sensor has to be read out 3 times at v2.x?

Three different programs with data so when we build category we go through the program numbers in order and called sensor every time.
BME280 will queried 5 times. %) But it works with it.

**Comment by dukess** [comment]
Fine!

**Comment by 1coderookie** [comment]
Did any changes occur with the query of DS18B20 also? Should I check with (multiple?) DS18B20, just to make sure..?

**Comment by dukess** [comment]
Hope Dallas has no quirks. But yes DS sensors will called twice: for temperature value and serial number.

**Comment by 1coderookie** [comment]
Ok so I'll test it - just to make sure that everything works as expected ;)

**Comment by 1coderookie** [comment]
Nice, quick test with 4 sensors at pin 7 - works :)
![Bildschirmfoto von 2021-01-31 12-59-33](https://user-images.githubusercontent.com/25869362/106383114-422e4300-63c4-11eb-9650-748f17a0f332.png)
