### ISSUE TITLE
Rounding/type cast issue with parameters of type VT_HOURS

### ISSUE THREAD

**Issue by hypetsch** [fredlcore/bsb_lan#36]
Recently I noticed that parameter 8570 (Betriebsstunden Feststoffkessel) shows a different value in BSB LAN web interface than in the heating system itself.

The value shown in the web UI is 748 whereas the heating controller shows 749.
I traced the data sent by the system:
```
DISP->HEIZ QUR 8570 Diagnose Erzeuger -  Betr'std Feststoffkessel: 
DC 8A 00 0B 06 3D 51 08 92 32 9C 
HEIZ->DISP ANS 8570 Diagnose Erzeuger -  Betr'std Feststoffkessel: 748 h
DC 80 0A 10 07 51 3D 08 92 00 00 29 20 20 56 FB
```
It seems there is a rounding issue / type cast issue when interpreting the value:
```
  hex: 0x292020 -> dec: 2695200
  2695200 / 3600 = 748,666
```
I think the issue is in line [BSB_lan.ino:1262](https://github.com/fredlcore/bsb_lan/blob/10e4225dbb08b581ac825dfbea71628824b1aea6/BSB_lan.ino#L1262) where the value is calculated as 
```
lval=((long(msg[pl_start+1])<<24)+(long(msg[pl_start+2])<<16)+(long(msg[pl_start+3])<<8)+long(msg[pl_start+4]))/divider;
```

As `VT_MINUTES` also uses `printDWORD(...)` with `divider != 1` it might also be affected.

**Comment by fredlcore** [comment]
Thanks a lot for this accurate observation. It is true that this function basically just cuts off the non-integer part of the value and does not proper rounding. However, in the end it is a matter of perspective whether you want to know the full hours that have passed (which is what the current function does), so thet 1 hour and 45 minutes still count as 1 hour. Or if you want it to be rounded up to 2 hours (whicht the heater does). Methematically, the latter is correct, but the impact is negligible, and given the rest of the ToDo list, it is unlikely that I'll have time to adjust this. However, I'd be happy to accept a pull request in case you find the time (and solution) for this issue.
