### ISSUE TITLE
Housing for BSB LAN Gateway

### ISSUE THREAD

**Issue by hacki11** [fredlcore/bsb_lan#41]
Hi,

just wanted to know if you can recommend any housing/case for the hardware.
Doesn't matter if print by myself or if there is already a product available

**Comment by hacki11** [comment]
I took an standard case from conrad.
![IMG_2854](https://user-images.githubusercontent.com/15319906/66196655-34b25d00-e699-11e9-95b7-195d020901d4.jpg)
![IMG_2855](https://user-images.githubusercontent.com/15319906/66196657-34b25d00-e699-11e9-92a2-215af6944e10.jpg)
![IMG_2858](https://user-images.githubusercontent.com/15319906/66196658-34b25d00-e699-11e9-8bda-272f3e3ccd92.jpg)

**Comment by fredlcore** [comment]
FHEM user EPo has provided us with a customized case to print with a 3D printer. The STL files can now be found in the "schematics" subdirectory.
