### ISSUE TITLE
Wrong command_ref for GPIO

### ISSUE THREAD

**Issue by seb821** [fredlcore/bsb_lan#56]
It looks like the Cheatsheet URL-commands are not good for GPIO.

Indeed, the syntax with comma was not working. This example works : /G5=1

**Comment by fredlcore** [comment]
Yes, you are correct, the correct syntax is /Gxx=y where xx is the digital pin and y is the value you want to set it to. To read inputs from the pin, you use /Gxx,I to set the pin to input mode and then display the read value.
