### ISSUE TITLE
feature request: Aktuelle Einstellungen/Werte Export/Import Funktion

### ISSUE THREAD

**Issue by feurer98** [fredlcore/bsb_lan#62]
Bei der Integration des Adapters in Loxone schreibe ich mir momentan die Aktuellen Werten von Hand raus, um bei einer fehlüberlegung die letzten Korrekt arbeiteten Werte einzutragen.

Ich vermisse hier eine Möglichkeit die aktuellen Einstellungen auf die SD Karte zu Exportieren.
Um diese natürlich auch wider einspielen zu können darf auch eine Import Funktion nicht fehlen.

**Comment by fredlcore** [comment]
Welche Einstellungen meinst Du? Die von BSB-LAN? Das sind nur eine Hand voll, die aber über die _confug.h fest einkompiliert werden und nach einem Neustart ja eh wieder zur Verfügung stehen.

Oder meinst Du die Einstellungen Deiner Heizung? Die kannst Du schon jetzt über
htto://<ip>/0-9999
schon jetzt komplett auslesen.

Das nicht überwachte Rückspielen von mehreren 1000 Parametern, die auch teilweise situationsabhängig sind, halte ich für keine gute Idee.
