### ISSUE TITLE
Möglichkeit, das auf einen esp8266 oder esp32 zu portieren?

### ISSUE THREAD

**Issue by red-gee** [fredlcore/bsb_lan#75]
Hallo besteht die Möglichkeit das auch für einen ESP8266/ESP32 zurecht zu stricken? Es wäre schön, da der ESP ja auch die direkte Möglichkeit hat, ihn über WLan anzusprechen.

**Comment by fredlcore** [comment]
Theoretisch vielleicht, aber warum? Dem ESP8266 fehlt ein zweiter serieller Port, und ein ESP würde all diejenigen ausschließen, die aus Sicherheitsgründen oder wegen des schlechten WLAN-Empfangs unter dem Dach oder im Keller (oder wo auch immer die Heizung steht) kein LAN verwenden können. Für 10-20 Euro bekommt man eine WLAN-LAN-Bridge, mit der man auch den Arduino ans WLAN bringen kann, und das sehr viel stabiler, als es dem ESP möglich wäre.

**Comment by red-gee** [comment]
danke für deine Antwort

**Comment by 1coderookie** [comment]
@red-gee: Mittlerweile sind zwei Möglichkeiten bzgl einer ESP-Verwendung gegeben:
1. Arduino Due + Adapter + ESP8266 anstelle des LAN-Shields
2. ESP32 + Adapter anstelle von Due+LAN-Shield/ESP8266
Wenn du also eine reine WLAN-Anbindung wünschst, dann ist vermutlich die zweite Variante empfehlenswert. Für eine bestimmte ESP32-NodeMCU-Boardvariante gibt es jetzt auch einen spezifischen Adapter. Alle Infos findest du im Handbuch im [Kap. 12](https://1coderookie.github.io/BSB-LPB-LAN/kap12.html)
