### ISSUE TITLE
Immergas support

### ISSUE THREAD

**Issue by djxela** [fredlcore/bsb_lan#85]
Hi,

Does it support Immergas Victrix boilers?

**Comment by fredlcore** [comment]
To be honest, I have never heard of these boilers. Do you have any more information on these? What kind of room controller is used and how is it connected? If it says anywhere on the board where you connect it to "BSB" or "CL+/CL-" or "FB" then chances are good.

**Comment by fredlcore** [comment]
In this document I found information about one of these boilers that would work with BSB-LAN:
http://www.vipsgas.cz/images/stories/soubory/navody/siemens/siemens-immergas-victrix-pro-sestava-1.pdf
The RVS63 is among the list of supported units. A full list can be found in our manual.
