### ISSUE TITLE
Print list of installed modules

### ISSUE THREAD

**Issue by dukess** [fredlcore/bsb_lan#99]
Frederick, are you interested in a patch for the /C command that prints a list of installed modules?
Output like this:
```
Installed modules:
WEBSERVER, IPWE, RESET, DebugTelnet, LOGGER, VERSION_CHECK
```

**Comment by fredlcore** [comment]
Yes, that would be nice, ideally as part of /C

**Comment by dukess** [comment]
Separate patch https://github.com/dukess/bsb_lan/commit/10e7b78f409db9c72c8e4ed6d8bb8a5de17d7ff3 
or in pull request https://github.com/fredlcore/bsb_lan/pull/100
